##### Atividade1 ######

# Gerar um relatório com os valores tabelados dos produtos e com os valores realmente executados nas vendas, exibindo a diferença entre esses valores e exibir a quantidade de produtos vendido por venda.

-- ORGANIZANDO A QUERY
SELECT  PRODUCTNAME, 
	P.UNITPRICE AS PRECO, 		 
	QUANTITY,
	ROUND(P.UNITPRICE - O.UNITPRICE,2) AS DESCONTO, 
	O.UNITPRICE AS PRECOFINAL 
FROM projeto.products AS P
INNER JOIN projeto.orderdetails as O
on P.productid = O.productid  
order by 4 desc
LIMIT 1000;

-- PREÇOS ABAIXO DO VALOR DE TABELA
SELECT COUNT(ROUND(P.UNITPRICE - O.UNITPRICE,2)) AS DESCONTO
FROM projeto.products AS P
INNER JOIN projeto.orderdetails as O
on P.productid = O.productid 
WHERE (P.UNITPRICE - O.UNITPRICE) != 0 -- OU PODERIA SER P.UNITPRICE > O.UNITPRICE
order by 1 desc
LIMIT 1000;
-- RETORNO DE 658 PRODUTOS COM DESCONTO


-- QUANTIDADES DE PRODUTOS QUE TIVERAM DESCONTANDO E A SOMA DOS DESCONTOS
SELECT  PRODUCTNAME, 
	COUNT(ROUND(P.UNITPRICE - O.UNITPRICE,2)) AS DESCONTO,
	ROUND(SUM(ROUND(P.UNITPRICE - O.UNITPRICE,2))) AS VALORES
FROM projeto.products AS P
INNER JOIN projeto.orderdetails as O
on P.productid = O.productid 
WHERE (P.UNITPRICE - O.UNITPRICE) != 0
GROUP BY 1 
order by 2 desc
LIMIT 1000;

-- QUERY MAIS COMPLETA COM QUANTIDADES POR VALOR FINAL
SELECT 
	PRODUCTNAME, 
	P.UNITPRICE AS PRECO,
	SUM(QUANTITY) AS QUANTIDADE, 		 
	ROUND(P.UNITPRICE - O.UNITPRICE,2) AS DESCONTO_UNITARIO, 
	O.UNITPRICE AS PRECO_UNITARIO,
	O.UNITPRICE * QUANTITY AS VALOR_FINAL
FROM projeto.products AS P
INNER JOIN projeto.orderdetails as O
on P.productid = O.productid
WHERE (P.UNITPRICE - O.UNITPRICE) != 0 
GROUP BY 1,2,5,6
ORDER BY 4 DESC
LIMIT 1000;

-- AGORA COM OS VALORES SOMADOS AS QUANTIDADES TOTAIS

SELECT PRODUCTNAME, 
		P.UNITPRICE AS PRECO_TABELADO,
		ROUND(P.UNITPRICE - O.UNITPRICE,2) AS DESCONTO_UNITARIO, 
		O.UNITPRICE AS PRECO_FINAL_UNIT,
		SUM(QUANTITY) AS QUANTIDADE, 		 
		ROUND(SUM(O.UNITPRICE * QUANTITY)) AS VALOR_TOTAL
FROM projeto.products AS P
INNER JOIN projeto.orderdetails as O
on P.productid = O.productid
WHERE (P.UNITPRICE - O.UNITPRICE) != 0 
GROUP BY 1,2,4
ORDER BY 3 DESC
LIMIT 1000;
